name: Staging deployment

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ohtuprothl/mielentila-app
          addLatest: true
          registry: docker.io
          buildArgs:
            PUBLIC_URL=https://ohtup-staging.cs.helsinki.fi/mielentilatutkimus
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Sleep
        run: sleep 240s
        shell: bash
        
      - name: Check production http status
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["https://ohtup-staging.cs.helsinki.fi/mielentilatutkimus/basic_information_form"]'
          expected: '[200]'
